### ISSUE TITLE
elFinderInput - class for input field

### ISSUE THREAD

**Issue by Ma3oBblu** [zxbodya/yii2-elfinder#3]
how can i put class for input field? tried 
`$form->field($sub,` "[$index]value")->widget(
                            ElFinderInput::className(),
                            [
                                'connectorRoute' => '/admin/pages/connector',
                                'options' => [
                                    'inputOptions' => ['class' => 'form-control'],
                                ]

```
                        ]
                    `)->label(false);
```

but it doesn't work

**Comment by zxbodya** [comment]
See pull request I created, generally it should work.

But I have not tested it - try it. If it works I will merge it.
